name: continuous integration

on: 
  push:
    branches:
      - "main"

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - name: Run user unit tests
        run: |
          npm install
          npm test