name: continuous integration

on: 
  push:
    branches:
      - "main"

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 16.14.2
      - name: Run unit tests
        run: npm test